version: "3.1"

networks:
  web:
    external: true

services:
  golinks:
    build: .
    container_name: golinks
    restart: always
    volumes:
      - ./data:/data
    environment:
      - SQLITE_PATH=/data/saved.sqlite
    labels:
      - traefik.backend=links
      - traefik.frontend.rule=Host:links.kumpf.home
      - traefik.docker.network=web
      - traefik.port=5555
    networks:
      - web